- name: Delete failed runs
  env:
    GH_TOKEN: ${{ secrets.PAT }}
    DRY_RUN: ${{ steps.config.outputs.DRY_RUN }}
    OLDER_THAN: ${{ steps.config.outputs.OLDER_THAN_DAYS }}
    WORKFLOW_FILE: ${{ steps.config.outputs.WORKFLOW_FILE }}
  run: |
    # Convert float to integer (1.0 → 1)
    DAYS_INT=$(printf "%.0f" "$OLDER_THAN")
    
    # Calculate cutoff date using integer
    CUTOFF=$(date -d "$DAYS_INT days ago" +%Y-%m-%d)
    
    echo "🔍 Scanning runs for: $WORKFLOW_FILE"
    echo "⏳ Older than: $CUTOFF ($DAYS_INT days)"
    echo "🛡️ Dry run: $DRY_RUN"

    # Rest of script remains the same...
    WORKFLOW_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
      "https://api.github.com/repos/${{ github.repository }}/actions/workflows" \
      | jq -r --arg WF "$WORKFLOW_FILE" '.workflows[] | select(.path == ".github/workflows/"+$WF) | .id')
    
    RUNS=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
      "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs?status=failure")
    
    echo "📊 Found $(echo "$RUNS" | jq '.total_count') failed runs"
    echo "$RUNS" | jq -r --arg CUTOFF "$CUTOFF" '
      .workflow_runs[] | 
      select(.created_at <= $CUTOFF) |
      "\(.id) | Run #\(.run_number) | \(.created_at) | \(.html_url)"
    ' | while read -r RUN_INFO; do
      RUN_ID=$(echo "$RUN_INFO" | awk '{print $1}')
      if [ "$DRY_RUN" = "true" ]; then
        echo "🚫 WOULD DELETE: $RUN_INFO"
      else
        echo "🗑️ DELETING: $RUN_INFO"
        curl -s -X DELETE -H "Authorization: Bearer $GH_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
      fi
    done